#if SKY_BRIGHTNESS == -1
#undef SKY_BRIGHTNESS
										#define SKY_BRIGHTNESS 0.75
#endif
#if SUN_BRIGHTNESS == -1
#undef SUN_BRIGHTNESS
										#define SUN_BRIGHTNESS 1.0
#endif
#if MOON_BRIGHTNESS == -1
#undef MOON_BRIGHTNESS
										#define MOON_BRIGHTNESS 1.0
#endif
#if CLOUDS_BRIGHTNESS == -1
#undef CLOUDS_BRIGHTNESS
										#define CLOUDS_BRIGHTNESS 0.75
#endif
#if DARKEN_SKY_UNDERGROUND == -1
#undef DARKEN_SKY_UNDERGROUND
										#define DARKEN_SKY_UNDERGROUND 1
#endif
#if STARS_BRIGHTNESS == -1
#undef STARS_BRIGHTNESS
										#define STARS_BRIGHTNESS 0.9
#endif
#if DARKEN_STARS_NEAR_BLOCKLIGHT == -1
#undef DARKEN_STARS_NEAR_BLOCKLIGHT
										#define DARKEN_STARS_NEAR_BLOCKLIGHT 1
#endif
#if DARKENED_STARS_BRIGHTNESS == -1
#undef DARKENED_STARS_BRIGHTNESS
										#define DARKENED_STARS_BRIGHTNESS 0.2
#endif
#if WEATHER_TRANSPARENCY == -1
#undef WEATHER_TRANSPARENCY
										#define WEATHER_TRANSPARENCY 0.0
#endif
#if CLOUD_TRANSPARENCY == -1
#undef CLOUD_TRANSPARENCY
										#define CLOUD_TRANSPARENCY 0.5
#endif
#if HIDE_NEARBY_CLOUDS == -1
#undef HIDE_NEARBY_CLOUDS
										#define HIDE_NEARBY_CLOUDS 0
#endif






#if FOG_ENABLED == -1
#undef FOG_ENABLED
										#define FOG_ENABLED 1
#endif
#if FOG_HEIGHT_SCALE == -1
#undef FOG_HEIGHT_SCALE
										#define FOG_HEIGHT_SCALE 3.0
#endif
#if FOG_EXTRA_CLOUDS_DISTANCE == -1
#undef FOG_EXTRA_CLOUDS_DISTANCE
										#define FOG_EXTRA_CLOUDS_DISTANCE 10.0
#endif
#if FOG_CURVE == -1
#undef FOG_CURVE
										#define FOG_CURVE 1
#endif



#if FOG_AIR_START == -1
#undef FOG_AIR_START
										#define FOG_AIR_START 0.5
#endif
#if FOG_AIR_END == -1
#undef FOG_AIR_END
										#define FOG_AIR_END 1.0
#endif
#if FOG_AIR_MIN == -1
#undef FOG_AIR_MIN
										#define FOG_AIR_MIN 0.02
#endif
#if FOG_AIR_RAIN_START == -1
#undef FOG_AIR_RAIN_START
										#define FOG_AIR_RAIN_START 0.0
#endif
#if FOG_AIR_RAIN_END == -1
#undef FOG_AIR_RAIN_END
										#define FOG_AIR_RAIN_END 1.0
#endif
#if FOG_AIR_RAIN_MIN == -1
#undef FOG_AIR_RAIN_MIN
										#define FOG_AIR_RAIN_MIN 0.2
#endif
#if FOG_WATER_START == -1
#undef FOG_WATER_START
										#define FOG_WATER_START 0.0
#endif
#if FOG_WATER_END == -1
#undef FOG_WATER_END
										#define FOG_WATER_END 150
#endif
#if FOG_WATER_MIN == -1
#undef FOG_WATER_MIN
										#define FOG_WATER_MIN 0.4
#endif
#if FOG_LAVA_START == -1
#undef FOG_LAVA_START
										#define FOG_LAVA_START 0.0
#endif
#if FOG_LAVA_END == -1
#undef FOG_LAVA_END
										#define FOG_LAVA_END 3
#endif
#if FOG_LAVA_MIN == -1
#undef FOG_LAVA_MIN
										#define FOG_LAVA_MIN 0.9
#endif
#if FOG_POWDERED_SNOW_START == -1
#undef FOG_POWDERED_SNOW_START
										#define FOG_POWDERED_SNOW_START 0.0
#endif
#if FOG_POWDERED_SNOW_END == -1
#undef FOG_POWDERED_SNOW_END
										#define FOG_POWDERED_SNOW_END 10
#endif
#if FOG_POWDERED_SNOW_MIN == -1
#undef FOG_POWDERED_SNOW_MIN
										#define FOG_POWDERED_SNOW_MIN 0.8
#endif






#if BLOCK_RED == -1
#undef BLOCK_RED
										#define BLOCK_RED 1.0
#endif
#if BLOCK_GREEN == -1
#undef BLOCK_GREEN
										#define BLOCK_GREEN 0.725
#endif
#if BLOCK_BLUE == -1
#undef BLOCK_BLUE
										#define BLOCK_BLUE 0.4
#endif
#if BLOCK_BRIGHTNESS == -1
#undef BLOCK_BRIGHTNESS
										#define BLOCK_BRIGHTNESS 0.9
#endif
#if BLOCK_BRIGHTNESS_CURVE == -1
#undef BLOCK_BRIGHTNESS_CURVE
										#define BLOCK_BRIGHTNESS_CURVE 3
#endif






#if CAVE_AMBIENT_RED == -1
#undef CAVE_AMBIENT_RED
										#define CAVE_AMBIENT_RED 1.0
#endif
#if CAVE_AMBIENT_GREEN == -1
#undef CAVE_AMBIENT_GREEN
										#define CAVE_AMBIENT_GREEN 0.8
#endif
#if CAVE_AMBIENT_BLUE == -1
#undef CAVE_AMBIENT_BLUE
										#define CAVE_AMBIENT_BLUE 0.75
#endif
#if CAVE_AMBIENT_BRIGHTNESS == -1
#undef CAVE_AMBIENT_BRIGHTNESS
										#define CAVE_AMBIENT_BRIGHTNESS 0.1
#endif






#if SKYLIGHT_DAY_RED == -1
#undef SKYLIGHT_DAY_RED
										#define SKYLIGHT_DAY_RED 1.05
#endif
#if SKYLIGHT_DAY_GREEN == -1
#undef SKYLIGHT_DAY_GREEN
										#define SKYLIGHT_DAY_GREEN 1.05
#endif
#if SKYLIGHT_DAY_BLUE == -1
#undef SKYLIGHT_DAY_BLUE
										#define SKYLIGHT_DAY_BLUE 1.0
#endif
#if SKYLIGHT_DAY_BRIGHTNESS == -1
#undef SKYLIGHT_DAY_BRIGHTNESS
										#define SKYLIGHT_DAY_BRIGHTNESS 4.0
#endif



#if AMBIENT_DAY_RED == -1
#undef AMBIENT_DAY_RED
										#define AMBIENT_DAY_RED 1.0
#endif
#if AMBIENT_DAY_GREEN == -1
#undef AMBIENT_DAY_GREEN
										#define AMBIENT_DAY_GREEN 1.0
#endif
#if AMBIENT_DAY_BLUE == -1
#undef AMBIENT_DAY_BLUE
										#define AMBIENT_DAY_BLUE 1.0
#endif
#if AMBIENT_DAY_BRIGHTNESS == -1
#undef AMBIENT_DAY_BRIGHTNESS
										#define AMBIENT_DAY_BRIGHTNESS 0.5
#endif






#if SKYLIGHT_NIGHT_RED == -1
#undef SKYLIGHT_NIGHT_RED
										#define SKYLIGHT_NIGHT_RED 1.0
#endif
#if SKYLIGHT_NIGHT_GREEN == -1
#undef SKYLIGHT_NIGHT_GREEN
										#define SKYLIGHT_NIGHT_GREEN 1.0
#endif
#if SKYLIGHT_NIGHT_BLUE == -1
#undef SKYLIGHT_NIGHT_BLUE
										#define SKYLIGHT_NIGHT_BLUE 1.0
#endif
#if SKYLIGHT_NIGHT_BRIGHTNESS == -1
#undef SKYLIGHT_NIGHT_BRIGHTNESS
										#define SKYLIGHT_NIGHT_BRIGHTNESS 0.3
#endif



#if AMBIENT_NIGHT_RED == -1
#undef AMBIENT_NIGHT_RED
										#define AMBIENT_NIGHT_RED 0.5
#endif
#if AMBIENT_NIGHT_GREEN == -1
#undef AMBIENT_NIGHT_GREEN
										#define AMBIENT_NIGHT_GREEN 0.6
#endif
#if AMBIENT_NIGHT_BLUE == -1
#undef AMBIENT_NIGHT_BLUE
										#define AMBIENT_NIGHT_BLUE 1.0
#endif
#if AMBIENT_NIGHT_BRIGHTNESS == -1
#undef AMBIENT_NIGHT_BRIGHTNESS
										#define AMBIENT_NIGHT_BRIGHTNESS 0.25
#endif






#if SKYLIGHT_SUNRISE_RED == -1
#undef SKYLIGHT_SUNRISE_RED
										#define SKYLIGHT_SUNRISE_RED 1.1
#endif
#if SKYLIGHT_SUNRISE_GREEN == -1
#undef SKYLIGHT_SUNRISE_GREEN
										#define SKYLIGHT_SUNRISE_GREEN 0.8
#endif
#if SKYLIGHT_SUNRISE_BLUE == -1
#undef SKYLIGHT_SUNRISE_BLUE
										#define SKYLIGHT_SUNRISE_BLUE 0.1
#endif
#if SKYLIGHT_SUNRISE_BRIGHTNESS == -1
#undef SKYLIGHT_SUNRISE_BRIGHTNESS
										#define SKYLIGHT_SUNRISE_BRIGHTNESS 7.0
#endif



#if AMBIENT_SUNRISE_RED == -1
#undef AMBIENT_SUNRISE_RED
										#define AMBIENT_SUNRISE_RED 1.0
#endif
#if AMBIENT_SUNRISE_GREEN == -1
#undef AMBIENT_SUNRISE_GREEN
										#define AMBIENT_SUNRISE_GREEN 1.0
#endif
#if AMBIENT_SUNRISE_BLUE == -1
#undef AMBIENT_SUNRISE_BLUE
										#define AMBIENT_SUNRISE_BLUE 1.0
#endif
#if AMBIENT_SUNRISE_BRIGHTNESS == -1
#undef AMBIENT_SUNRISE_BRIGHTNESS
										#define AMBIENT_SUNRISE_BRIGHTNESS 0.3
#endif






#if SKYLIGHT_SUNSET_RED == -1
#undef SKYLIGHT_SUNSET_RED
										#define SKYLIGHT_SUNSET_RED 1.3
#endif
#if SKYLIGHT_SUNSET_GREEN == -1
#undef SKYLIGHT_SUNSET_GREEN
										#define SKYLIGHT_SUNSET_GREEN 0.5
#endif
#if SKYLIGHT_SUNSET_BLUE == -1
#undef SKYLIGHT_SUNSET_BLUE
										#define SKYLIGHT_SUNSET_BLUE 0.0
#endif
#if SKYLIGHT_SUNSET_BRIGHTNESS == -1
#undef SKYLIGHT_SUNSET_BRIGHTNESS
										#define SKYLIGHT_SUNSET_BRIGHTNESS 7.0
#endif



#if AMBIENT_SUNSET_RED == -1
#undef AMBIENT_SUNSET_RED
										#define AMBIENT_SUNSET_RED 1.0
#endif
#if AMBIENT_SUNSET_GREEN == -1
#undef AMBIENT_SUNSET_GREEN
										#define AMBIENT_SUNSET_GREEN 1.0
#endif
#if AMBIENT_SUNSET_BLUE == -1
#undef AMBIENT_SUNSET_BLUE
										#define AMBIENT_SUNSET_BLUE 1.0
#endif
#if AMBIENT_SUNSET_BRIGHTNESS == -1
#undef AMBIENT_SUNSET_BRIGHTNESS
										#define AMBIENT_SUNSET_BRIGHTNESS 0.3
#endif












#if SHADOWS_ENABLED == -1
#undef SHADOWS_ENABLED
										#define SHADOWS_ENABLED 1
#endif
#if EXCLUDE_FOLIAGE == -1
#undef EXCLUDE_FOLIAGE
										#define EXCLUDE_FOLIAGE 0
#endif
#if SHADOW_FILTERING == -1
#undef SHADOW_FILTERING
										#define SHADOW_FILTERING 2
#endif
#if SHADOWS_NOISE == -1
#undef SHADOWS_NOISE
										#define SHADOWS_NOISE 0.3
#endif
#if SHADOW_DISTORT_ADDITION == -1
#undef SHADOW_DISTORT_ADDITION
										#define SHADOW_DISTORT_ADDITION 0.09
#endif
#if PIXELATED_SHADOWS == -1
#undef PIXELATED_SHADOWS
										#define PIXELATED_SHADOWS 0
#endif
#if SIDE_SHADING == -1
#undef SIDE_SHADING
										#define SIDE_SHADING 0.0
#endif
#if RAIN_LIGHT_MULT == -1
#undef RAIN_LIGHT_MULT
										#define RAIN_LIGHT_MULT 0.7
#endif
#if USE_VANILLA_BRIGHTNESS == -1
#undef USE_VANILLA_BRIGHTNESS
										#define USE_VANILLA_BRIGHTNESS 1
#endif
#if BLOCKLIGHT_FLICKERING_ENABLED == -1
#undef BLOCKLIGHT_FLICKERING_ENABLED
										#define BLOCKLIGHT_FLICKERING_ENABLED 1
#endif






#if HANDHELD_LIGHT_ENABLED == -1
#undef HANDHELD_LIGHT_ENABLED
										#define HANDHELD_LIGHT_ENABLED 1
#endif
#if HANDHELD_LIGHT_DISTANCE == -1
#undef HANDHELD_LIGHT_DISTANCE
										#define HANDHELD_LIGHT_DISTANCE 25
#endif
#if HANDHELD_LIGHT_BRIGHTNESS == -1
#undef HANDHELD_LIGHT_BRIGHTNESS
										#define HANDHELD_LIGHT_BRIGHTNESS 1.0
#endif












#if REFLECTIONS_ENABLED == -1
#undef REFLECTIONS_ENABLED
										#define REFLECTIONS_ENABLED 1
#endif




#if WATER_REFLECTION_AMOUNT == -1
#undef WATER_REFLECTION_AMOUNT
										#define WATER_REFLECTION_AMOUNT 0.7
#endif
#if WATER_REFLECTION_FRESNEL == -1
#undef WATER_REFLECTION_FRESNEL
										#define WATER_REFLECTION_FRESNEL 0.8
#endif



#if RAIN_REFLECTION_COVERAGE == -1
#undef RAIN_REFLECTION_COVERAGE
										#define RAIN_REFLECTION_COVERAGE 0.4
#endif
#if RAIN_REFLECTION_MIN == -1
#undef RAIN_REFLECTION_MIN
										#define RAIN_REFLECTION_MIN 0.2
#endif
#if RAIN_REFLECTION_SLOPE == -1
#undef RAIN_REFLECTION_SLOPE
										#define RAIN_REFLECTION_SLOPE 2.0
#endif
#if RAIN_REFLECTION_AMOUNT == -1
#undef RAIN_REFLECTION_AMOUNT
										#define RAIN_REFLECTION_AMOUNT 0.9
#endif
#if RAIN_REFLECTION_FRESNEL == -1
#undef RAIN_REFLECTION_FRESNEL
										#define RAIN_REFLECTION_FRESNEL 0.3
#endif



#if REFLECTION_ITERATIONS == -1
#undef REFLECTION_ITERATIONS
										#define REFLECTION_ITERATIONS 40
#endif
#if REFLECTION_STEP_INCREASE == -1
#undef REFLECTION_STEP_INCREASE
										#define REFLECTION_STEP_INCREASE 1.1
#endif






#if SSAO_ENABLED == -1
#undef SSAO_ENABLED
										#define SSAO_ENABLED 1
#endif
#if AO_AMOUNT == -1
#undef AO_AMOUNT
										#define AO_AMOUNT 1.0
#endif
#if AO_SIZE == -1
#undef AO_SIZE
										#define AO_SIZE 2.5
#endif
#if AO_QUALITY == -1
#undef AO_QUALITY
										#define AO_QUALITY 3
#endif
#if SSAO_APPLICATION_TYPE == -1
#undef SSAO_APPLICATION_TYPE
										#define SSAO_APPLICATION_TYPE 1
#endif






#if BLOOM_ENABLED == -1
#undef BLOOM_ENABLED
										#define BLOOM_ENABLED 1
#endif
#if BLOOM_AMOUNT == -1
#undef BLOOM_AMOUNT
										#define BLOOM_AMOUNT 2.5
#endif
#if BLOOM_QUALITY == -1
#undef BLOOM_QUALITY
										#define BLOOM_QUALITY 3
#endif
#if BLOOM_COMPUTE_COUNT == -1
#undef BLOOM_COMPUTE_COUNT
										#define BLOOM_COMPUTE_COUNT 1
#endif
#if BLOOM_LOW_CUTOFF == -1
#undef BLOOM_LOW_CUTOFF
										#define BLOOM_LOW_CUTOFF 0.0
#endif
#if BLOOM_HIGH_CUTOFF == -1
#undef BLOOM_HIGH_CUTOFF
										#define BLOOM_HIGH_CUTOFF 1.0
#endif
#if BLOOM_SIZE == -1
#undef BLOOM_SIZE
										#define BLOOM_SIZE 2.5
#endif
#if BLOOM_NETHER_MULT == -1
#undef BLOOM_NETHER_MULT
										#define BLOOM_NETHER_MULT 2.0
#endif






#if DEPTH_SUNRAYS_ENABLED == -1
#undef DEPTH_SUNRAYS_ENABLED
										#define DEPTH_SUNRAYS_ENABLED 0
#endif
#if VOL_SUNRAYS_ENABLED == -1
#undef VOL_SUNRAYS_ENABLED
										#define VOL_SUNRAYS_ENABLED 1
#endif
#if SUNRAYS_STYLE == -1
#undef SUNRAYS_STYLE
										#define SUNRAYS_STYLE 1
#endif
#if SUNRAYS_QUALITY == -1
#undef SUNRAYS_QUALITY
										#define SUNRAYS_QUALITY 4
#endif
#if SUNRAYS_COMPUTE_COUNT == -1
#undef SUNRAYS_COMPUTE_COUNT
										#define SUNRAYS_COMPUTE_COUNT 1
#endif
#if SUNRAYS_FLICKERING_FIX == -1
#undef SUNRAYS_FLICKERING_FIX
										#define SUNRAYS_FLICKERING_FIX 0
#endif
#if SUNRAYS_AMOUNT_DAY == -1
#undef SUNRAYS_AMOUNT_DAY
										#define SUNRAYS_AMOUNT_DAY 0.4
#endif
#if SUNRAYS_AMOUNT_NIGHT == -1
#undef SUNRAYS_AMOUNT_NIGHT
										#define SUNRAYS_AMOUNT_NIGHT 0.05
#endif
#if SUNRAYS_AMOUNT_SUNRISE == -1
#undef SUNRAYS_AMOUNT_SUNRISE
										#define SUNRAYS_AMOUNT_SUNRISE 0.4
#endif
#if SUNRAYS_AMOUNT_SUNSET == -1
#undef SUNRAYS_AMOUNT_SUNSET
										#define SUNRAYS_AMOUNT_SUNSET 0.4
#endif
#if SUNRAYS_SUN_RED == -1
#undef SUNRAYS_SUN_RED
										#define SUNRAYS_SUN_RED 1.0
#endif
#if SUNRAYS_SUN_GREEN == -1
#undef SUNRAYS_SUN_GREEN
										#define SUNRAYS_SUN_GREEN 1.0
#endif
#if SUNRAYS_SUN_BLUE == -1
#undef SUNRAYS_SUN_BLUE
										#define SUNRAYS_SUN_BLUE 0.7
#endif
#if SUNRAYS_MOON_RED == -1
#undef SUNRAYS_MOON_RED
										#define SUNRAYS_MOON_RED 0.6
#endif
#if SUNRAYS_MOON_GREEN == -1
#undef SUNRAYS_MOON_GREEN
										#define SUNRAYS_MOON_GREEN 0.7
#endif
#if SUNRAYS_MOON_BLUE == -1
#undef SUNRAYS_MOON_BLUE
										#define SUNRAYS_MOON_BLUE 1.0
#endif






#if DOF_ENABLED == -1
#undef DOF_ENABLED
										#define DOF_ENABLED 1
#endif
#if DOF_NEAR_BLUR_START == -1
#undef DOF_NEAR_BLUR_START
										#define DOF_NEAR_BLUR_START 0.03
#endif
#if DOF_NEAR_BLUR_SLOPE == -1
#undef DOF_NEAR_BLUR_SLOPE
										#define DOF_NEAR_BLUR_SLOPE 0.05
#endif
#if DOF_NEAR_BLUR_STRENGTH == -1
#undef DOF_NEAR_BLUR_STRENGTH
										#define DOF_NEAR_BLUR_STRENGTH 0.6
#endif
#if DOF_NEAR_BLUR_SIZE == -1
#undef DOF_NEAR_BLUR_SIZE
										#define DOF_NEAR_BLUR_SIZE 2.0
#endif
#if DOF_FAR_BLUR_START == -1
#undef DOF_FAR_BLUR_START
										#define DOF_FAR_BLUR_START 0.03
#endif
#if DOF_FAR_BLUR_SLOPE == -1
#undef DOF_FAR_BLUR_SLOPE
										#define DOF_FAR_BLUR_SLOPE 0.15
#endif
#if DOF_FAR_BLUR_STRENGTH == -1
#undef DOF_FAR_BLUR_STRENGTH
										#define DOF_FAR_BLUR_STRENGTH 0.4
#endif
#if DOF_FAR_BLUR_SIZE == -1
#undef DOF_FAR_BLUR_SIZE
										#define DOF_FAR_BLUR_SIZE 5.0
#endif
#if DOF_SLOPE_TYPE == -1
#undef DOF_SLOPE_TYPE
										#define DOF_SLOPE_TYPE 1
#endif
#if DOF_LOCKED_FOCAL_PLANE == -1
#undef DOF_LOCKED_FOCAL_PLANE
										#define DOF_LOCKED_FOCAL_PLANE 0
#endif
#if DOF_FOCAL_PLANE_DISTANCE == -1
#undef DOF_FOCAL_PLANE_DISTANCE
										#define DOF_FOCAL_PLANE_DISTANCE 10
#endif






#if TAA_ENABLED == -1
#undef TAA_ENABLED
										#define TAA_ENABLED 1
#endif






#if MOTION_BLUR_ENABLED == -1
#undef MOTION_BLUR_ENABLED
										#define MOTION_BLUR_ENABLED 0
#endif
#if MOTION_BLUR_AMOUNT == -1
#undef MOTION_BLUR_AMOUNT
										#define MOTION_BLUR_AMOUNT 0.5
#endif
#if MOTION_BLUR_QUALITY == -1
#undef MOTION_BLUR_QUALITY
										#define MOTION_BLUR_QUALITY 3
#endif






#if SHARPENING_ENABLED == -1
#undef SHARPENING_ENABLED
										#define SHARPENING_ENABLED 1
#endif
#if SHARPEN_AMOUNT == -1
#undef SHARPEN_AMOUNT
										#define SHARPEN_AMOUNT 0.3
#endif
#if SHARPEN_VEL_ADDITION == -1
#undef SHARPEN_VEL_ADDITION
										#define SHARPEN_VEL_ADDITION 1.3
#endif
#if SHARPENING_DETECT_SIZE == -1
#undef SHARPENING_DETECT_SIZE
										#define SHARPENING_DETECT_SIZE 5
#endif






#if GAMMA == -1
#undef GAMMA
										#define GAMMA 0
#endif
#if BRIGHTNESS == -1
#undef BRIGHTNESS
										#define BRIGHTNESS 1.1
#endif



#if SATURATION == -1
#undef SATURATION
										#define SATURATION 0.0
#endif
#if SATURATION_DARK == -1
#undef SATURATION_DARK
										#define SATURATION_DARK 0.1
#endif
#if SATURATION_LIGHT == -1
#undef SATURATION_LIGHT
										#define SATURATION_LIGHT -0.3
#endif



#if VIBRANCE == -1
#undef VIBRANCE
										#define VIBRANCE 0.0
#endif



#if CONTRAST == -1
#undef CONTRAST
										#define CONTRAST -0.1
#endif
#if CONTRAST_DETECT_RED == -1
#undef CONTRAST_DETECT_RED
										#define CONTRAST_DETECT_RED 0.5
#endif
#if CONTRAST_DETECT_GREEN == -1
#undef CONTRAST_DETECT_GREEN
										#define CONTRAST_DETECT_GREEN 0.5
#endif
#if CONTRAST_DETECT_BLUE == -1
#undef CONTRAST_DETECT_BLUE
										#define CONTRAST_DETECT_BLUE 0.5
#endif



#if TONEMAPPER == -1
#undef TONEMAPPER
										#define TONEMAPPER 0
#endif
#if USE_GAMMA_CORRECTION == -1
#undef USE_GAMMA_CORRECTION
										#define USE_GAMMA_CORRECTION 0
#endif






#if COLORBLIND_MODE == -1
#undef COLORBLIND_MODE
										#define COLORBLIND_MODE 0
#endif
#if COLORBLIND_INTENSITY == -1
#undef COLORBLIND_INTENSITY
										#define COLORBLIND_INTENSITY 1.0
#endif






#if VIGNETTE_ENABLED == -1
#undef VIGNETTE_ENABLED
										#define VIGNETTE_ENABLED 1
#endif
#if VIGNETTE_AMOUNT_SURFACE == -1
#undef VIGNETTE_AMOUNT_SURFACE
										#define VIGNETTE_AMOUNT_SURFACE 0.0
#endif
#if VIGNETTE_AMOUNT_UNDERGROUND == -1
#undef VIGNETTE_AMOUNT_UNDERGROUND
										#define VIGNETTE_AMOUNT_UNDERGROUND 0.8
#endif
#if VIGNETTE_SCALE == -1
#undef VIGNETTE_SCALE
										#define VIGNETTE_SCALE 1.0
#endif
#if VIGNETTE_NOISE_ENABLED == -1
#undef VIGNETTE_NOISE_ENABLED
										#define VIGNETTE_NOISE_ENABLED 1
#endif






#if WAVING_ENABLED == -1
#undef WAVING_ENABLED
										#define WAVING_ENABLED 1
#endif
#if WAVING_SPEED == -1
#undef WAVING_SPEED
										#define WAVING_SPEED 1.5
#endif
#if WAVING_WORLD_SCALE == -1
#undef WAVING_WORLD_SCALE
										#define WAVING_WORLD_SCALE 0.15
#endif
#if WAVING_AMOUNT_1 == -1
#undef WAVING_AMOUNT_1
										#define WAVING_AMOUNT_1 0.5
#endif
#if WAVING_AMOUNT_2 == -1
#undef WAVING_AMOUNT_2
										#define WAVING_AMOUNT_2 0.75
#endif
#if WAVING_AMOUNT_3 == -1
#undef WAVING_AMOUNT_3
										#define WAVING_AMOUNT_3 1.5
#endif
#if WAVING_RAIN_MULT == -1
#undef WAVING_RAIN_MULT
										#define WAVING_RAIN_MULT 3.0
#endif
#if WAVING_NIGHT_MULT == -1
#undef WAVING_NIGHT_MULT
										#define WAVING_NIGHT_MULT 0.1
#endif
#if HEIGHT_BASED_WAVING_ENABLED == -1
#undef HEIGHT_BASED_WAVING_ENABLED
										#define HEIGHT_BASED_WAVING_ENABLED 1
#endif



#if PHYSICALLY_WAVING_WATER_ENABLED == -1
#undef PHYSICALLY_WAVING_WATER_ENABLED
										#define PHYSICALLY_WAVING_WATER_ENABLED 1
#endif
#if WAVING_WATER_NORMALS_ENABLED == -1
#undef WAVING_WATER_NORMALS_ENABLED
										#define WAVING_WATER_NORMALS_ENABLED 1
#endif



#if UNDERWATER_WAVINESS_ENABLED == -1
#undef UNDERWATER_WAVINESS_ENABLED
										#define UNDERWATER_WAVINESS_ENABLED 1
#endif
#if UNDERWATER_WAVINESS_AMOUNT == -1
#undef UNDERWATER_WAVINESS_AMOUNT
										#define UNDERWATER_WAVINESS_AMOUNT 1.0
#endif
#if UNDERWATER_WAVINESS_SCALE == -1
#undef UNDERWATER_WAVINESS_SCALE
										#define UNDERWATER_WAVINESS_SCALE 1.0
#endif
#if UNDERWATER_WAVINESS_SPEED == -1
#undef UNDERWATER_WAVINESS_SPEED
										#define UNDERWATER_WAVINESS_SPEED 1.0
#endif






#if WATER_FRESNEL_ADDITION == -1
#undef WATER_FRESNEL_ADDITION
										#define WATER_FRESNEL_ADDITION 1
#endif
#if WATER_TRANSPARENCY == -1
#undef WATER_TRANSPARENCY
										#define WATER_TRANSPARENCY 0.1
#endif






#if ISOMETRIC_RENDERING_ENABLED == -1
#undef ISOMETRIC_RENDERING_ENABLED
										#define ISOMETRIC_RENDERING_ENABLED 0
#endif
#if ISOMETRIC_WORLD_SCALE == -1
#undef ISOMETRIC_WORLD_SCALE
										#define ISOMETRIC_WORLD_SCALE 32
#endif
#if ISOMETRIC_BACKWARD_VISIBILITY == -1
#undef ISOMETRIC_BACKWARD_VISIBILITY
										#define ISOMETRIC_BACKWARD_VISIBILITY 1
#endif
#if ISOMETRIC_FORWARD_VISIBILITY == -1
#undef ISOMETRIC_FORWARD_VISIBILITY
										#define ISOMETRIC_FORWARD_VISIBILITY 128
#endif












#if USE_BETTER_RAND == -1
#undef USE_BETTER_RAND
										#define USE_BETTER_RAND 0
#endif
#if SHOW_DANGEROUS_LIGHT == -1
#undef SHOW_DANGEROUS_LIGHT
										#define SHOW_DANGEROUS_LIGHT 0
#endif
#if USE_SIMPLE_LIGHT == -1
#undef USE_SIMPLE_LIGHT
										#define USE_SIMPLE_LIGHT 0
#endif
#if SSAO_SHOW_AMOUNT == -1
#undef SSAO_SHOW_AMOUNT
										#define SSAO_SHOW_AMOUNT 0
#endif
#if BLOOM_SHOW_ADDITION == -1
#undef BLOOM_SHOW_ADDITION
										#define BLOOM_SHOW_ADDITION 0
#endif
#if BLOOM_SHOW_FILTERED_TEXTURE == -1
#undef BLOOM_SHOW_FILTERED_TEXTURE
										#define BLOOM_SHOW_FILTERED_TEXTURE 0
#endif
#if SUNRAYS_SHOW_ADDITION == -1
#undef SUNRAYS_SHOW_ADDITION
										#define SUNRAYS_SHOW_ADDITION 0
#endif
#if DOF_SHOW_AMOUNTS == -1
#undef DOF_SHOW_AMOUNTS
										#define DOF_SHOW_AMOUNTS 0
#endif
#if REFLECTIVE_EVERYTHING == -1
#undef REFLECTIVE_EVERYTHING
										#define REFLECTIVE_EVERYTHING 0
#endif
